// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXMD_6rQZ4LqK9ffe2TLxnSkFjVmC-k8',
    appId: '1:837291705741:web:260166b3aa230d0f3f69c4',
    messagingSenderId: '837291705741',
    projectId: 'uberclone-63e86',
    authDomain: 'uberclone-63e86.firebaseapp.com',
    storageBucket: 'uberclone-63e86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWm_qE3gm6aP6GFKdOGs3w7KlnquQaPg',
    appId: '1:837291705741:android:82460c048aa7b0ff3f69c4',
    messagingSenderId: '837291705741',
    projectId: 'uberclone-63e86',
    storageBucket: 'uberclone-63e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdzNBi9HkLMbgbAzc0pZ3A0BVqIcSZDVE',
    appId: '1:837291705741:ios:53d0dcfecc1da3bf3f69c4',
    messagingSenderId: '837291705741',
    projectId: 'uberclone-63e86',
    storageBucket: 'uberclone-63e86.appspot.com',
    iosBundleId: 'com.example.uberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdzNBi9HkLMbgbAzc0pZ3A0BVqIcSZDVE',
    appId: '1:837291705741:ios:bab80abe7c9d74423f69c4',
    messagingSenderId: '837291705741',
    projectId: 'uberclone-63e86',
    storageBucket: 'uberclone-63e86.appspot.com',
    iosBundleId: 'com.example.uberapp.RunnerTests',
  );
}
